from collections.abc import Iterable

class ExtClass:
    def __init__(self, n: int) -> None: ...
    def get(self) -> int: ...
    def set(self, n: int) -> None: ...

class vec_uint64_t:  # noqa: N801
    def __init__(self, v: Iterable[int]) -> None: ...

def mutate(v: vec_uint64_t) -> None: ...
